#dubbo配置
dubbo:
  application:
    id: springboot-dubbo-provider
    name: springboot-dubbo-provider
    qos:
      port: 22222
      enable: true
  #协议配置
  protocol:
    id: dubbo
    name: dubbo
    port: 12345
    status: server
  #服务注册配置
  registry:
    id: my-registry
    address: N/A
endpoints:
  dubbo:
    enabled: true
#dubbo健康监控
management:
  health:
    dubbo:
      status:
        defaults: memory
        extras: load,threadpool
